### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by benpoulson** [apecloud/myduckserver#133]
Currently MariaDB is not supported due to different gtid implementations. Will have a play around and see if I can add support.

**Comment by fanyang01** [comment]
Thank you for reporting this compatibility issue. MariaDB support is indeed on our near-term roadmap, but we haven't tested this project with it yet. The Vitess binlog subscriber does support MariaDB, so adding support for it should be straightforward.

**Comment by fanyang01** [comment]
Here’s the updated message:

---

Hi @benpoulson,

@NoyException has added support for replication from MariaDB. We would appreciate it if you could test it in your setup and let us know if it works as expected.
