### ISSUE TITLE
Does it support MyISAM  storage engine？

### ISSUE THREAD

**Issue by snamper** [apecloud/myduckserver#142]
It supplier MyISAM  storage engine，sync is ok？

**Comment by GaoYusong** [comment]
While we haven’t tested the MyISAM storage engine, MyDuckServer relies solely on binlog for synchronization, so it should work in theory. If you run into any issues, please feel free to open an issue, and we’ll address it promptly.

**Comment by VWagen1989** [comment]
I've tested the replication on MyISAM. Both snapshot and incremental replication work. I think you can try this. And please don't forget to open issues for the problems you met in your trial.
