### ISSUE TITLE
 Does it support data persistence to object storage?

### ISSUE THREAD

**Issue by wking1986** [apecloud/myduckserver#145]
Does MyDuck Sever support data persistence to object storage（eg. S3 , COS）?

**Comment by fanyang01** [comment]
Thank you for your question! Object storage support is indeed on our roadmap. We're currently considering two main options: (1) writing data in a data lake format (e.g., Delta Lake), and (2) implementing an S3-based FUSE layer to serve DuckDB. Stay tuned!

**Comment by TianyuZhang1214** [comment]
Stay tuned for updates on this in #118!

**Comment by TianyuZhang1214** [comment]
@wking1986 
Hi, we’ve recently added support for [Backup/Restore](https://github.com/apecloud/myduckserver/blob/main/docs/tutorial/backup-restore.md). This feature allows you to back up your data in MyDuck Server to object storage services like S3, COS, or OSS, and restore a MyDuck Server instance from data stored in these services. We hope this functionality addresses part of your requirements! Let us know if you have additional feedback or needs.
