### ISSUE TITLE
Fail to replicate if a table has more than one primary/unique key

### ISSUE THREAD

**Issue by NoyException** [apecloud/myduckserver#152]
For example, I creates a table like this
```sql
create table account(
  id int, 
  name char(16) unique, 
  balance float, 
  primary key(id)
);
insert into account values(12500000, "name0", 514.35);
```

Then when I try to replica this from MariaDB to MyDuck, an error occurs:
```plaintext
ERROR: TGT: [worker000]: test@account@@0.tsv: MySQL Error 1105 (HY000): Binder Error: Conflict target has to be provided for a D0 UPDATE operation when the table has multiple UNIQUE/PRIMARY KEY constraints: LOAD DATA LOCAL INFILE 'memory/test@account@@0.tsv' REPLACE INTO TABLE `test`. `account` CHARACTER SET 'utf8mb4' FIELDS TERMINATED BY '   ' ESCAPED BY '\\' LINES STARTING BY '' TERMINATED BY '\n' (`id`, `name`, `balance` )
```

This error disappeared after removing `unique`.

**Comment by fanyang01** [comment]
Does this occur in the invocation of `mysqlsh`? If so, can we bypass it by using the `deferTableIndexes` options? https://dev.mysql.com/doc/mysql-shell/8.4/en/mysql-shell-utils-copy.html#:~:text=restrictions%20and%20configuration.-,deferTableIndexes,-%3A%20%5B%20off%20%7C%20fulltext%20%7C%20all

**Comment by fanyang01** [comment]
Interesting. Maybe we should investigate why `--defer-table-indexes all` isn't working. Is there anything noteworthy in the MySQL Shell log?

**Comment by fanyang01** [comment]
You can run `./myduckserver --loglevel 6` to observe whether the secondary index creation is actually defered. If not, you can search `deferTableIndexes ` in [MySQL Shell's source code](https://github.com/mysql/mysql-shell) to find why it does not take effect.
