### ISSUE TITLE
pg: `FORMAT TEXT` is not supported for `COPY FROM STDIN`

### ISSUE THREAD

**Issue by NoyException** [apecloud/myduckserver#157]
In `pgserver/connection_handler.go`, line 654:
```go
	switch copyFrom.Options.CopyFormat {
		case tree.CopyFormatText:
			// NewTextDataLoader is missing here
		case tree.CopyFormatCSV:
			dataLoader, err = NewCsvDataLoader(sqlCtx, h.duckHandler, insertableTable, copyFrom.Columns, &copyFrom.Options)
	}
```
The text format is ignored, which makes `dataLoader` still nil after nil check and causes a nil reference error when executing `COPY FROM stdin;`

**Comment by fanyang01** [comment]
This could be fixed by adding `fallthrough` or using `case tree.CopyFormatText, tree.CopyFormatCSV:`. Although the TEXT format is not fully compatible with CSV (see https://github.com/duckdb/duckdb/pull/14464 ), for common cases it should work well.

**Comment by fanyang01** [comment]
> But the txt format in pg_dump is delimited by consecutive Spaces

https://www.postgresql.org/docs/current/sql-copy.html#:~:text=this%20might%20cause.-,DELIMITER,-Specifies%20the%20character

Is it tab (`\t`) but displayed in your editor as 4 spaces?
