### ISSUE TITLE
Support "CREATE TEMPORARY TABLE"

### ISSUE THREAD

**Issue by ddh-5230** [apecloud/myduckserver#221]
mysql> use mydb;
Database changed
mysql> CREATE TEMPORARY TABLE stu (
    ->     student_id INTEGER,
    ->     name VARCHAR(10)
    -> );
ERROR 1105 (HY000): database does not support temporary tables

**Comment by fanyang01** [comment]
Done in https://github.com/apecloud/myduckserver/pull/223
