### ISSUE TITLE
Add support for `SQLite`

### ISSUE THREAD

**Issue by kuatroka** [apecloud/myduckserver#238]
Hi, any plans to add SQLite? Thanks

**Comment by TianyuZhang1214** [comment]
> Hi, any plans to add SQLite? Thanks

Thank you for your interest! Could you clarify whether you mean: 

1. Adding SQLite as a data source and synchronizing data from SQLite to MyDuck Server, or  
2. Using SQLite as a storage engine (as an alternative to DuckDB)?  

This will help us better understand your request. Looking forward to your input!

**Comment by TianyuZhang1214** [comment]
> The #1. To add a SQLite protocol to the existing Postgres and MySQL.

Hi,
Regarding your request to add a SQLite protocol alongside the existing PostgreSQL and MySQL protocols:

DuckDB now supports [reading data directly from SQLite databases](https://github.com/duckdb/sqlite_scanner). This functionality can be utilized by using the ATTACH command within the PostgreSQL protocol in MyDuck Server.

Does this meet your requirements? Or do you still need us to add SQLite as a data source and implement data synchronization from SQLite to MyDuck Server?

**Comment by kuatroka** [comment]
I think I made a mistake in my understanding of what myduckserver is. I thought it's like a add-on on top of MySQL or Postgres that adds duckdb functionality, but it's not so. I think we can close this ticket as what I want is a different beast. I want to have SQLite as my main DB, but with the duckdb functionality inside it. Thanks and sorry for confusion
