### ISSUE TITLE
Support multiple statements within one query

### ISSUE THREAD

**Issue by NoyException** [apecloud/myduckserver#261]
C# PostgreSQL clients send multiple statements within one query to build a connection, which is not currently supported yet. Can we add this feature in the future?

```
   Unhandled exception. System.Exception: Error connecting to database: XX000: only a single statement at a time is currently supported
    ---> Npgsql.PostgresException (0x80004005): XX000: only a single statement at a time is currently supported
```

**Comment by fanyang01** [comment]
Sure, it is a common usage. Let's look into this in the coming weeks.
