### ISSUE TITLE
How to init sql commands at boot time

### ISSUE THREAD

**Issue by thucnc** [apecloud/myduckserver#268]
Hi, I want to init some sql commands at docker instance startup, such as load extensions and declare secrects, may you help ?

**Comment by VWagen1989** [comment]
> Hi, I want to init some sql commands at docker instance startup, such as load extensions and declare secrects, may you help ?

Thanks for submitting this issue!

Sorry, currently the docker image of MyDuck Server can not accept customized initialization SQL statements during the procedure of booting. But this sounds like a good feature, we will do this later.

Before the implementation, may I ask what extensions you want to load? Extensions on postgreSQL or DuckDB?

In addtion, were you accessing the port based on PostgreSQL wire protocol or the MySQL one? The authentication based on PostgreSQL protocol is still working in progress, so only the accounts on the port based on MySQL protocol can be assigned with new passwords.

**Comment by VWagen1989** [comment]
> Hi @VWagen1989 . I want to use Postgresql protocol, and I want to setup some Duckdb extensions and Duckdb secrects at boot time. My desire is to use myduckserver in stateless mode to join other data sources such as s3/postgresql/big query.

Got it! So those initialization operations are expected to be performed on DuckDB. We will add a new parameter for MyDuck Server to accept customized initialization SQL statements. And we will reply in this issue once the new parameter is ready.

**Comment by VWagen1989** [comment]
Hi, @thucnc 
We have just resolved this issue by adding an initialization operation when MyDuck Server is ready. Please check the [usage here](https://github.com/apecloud/myduckserver?tab=readme-ov-file#initialize-myduck-server-with-custom-sqls).
Thurthermore, we also illustrated an example of installing extensions and creating secrets in the description of the latest PR. Please check this out: #271.

**Comment by VWagen1989** [comment]
@thucnc And please join our discord channel. We can discuss about this project on it: https://discord.gg/9MC5cgw5YK
