### ISSUE TITLE
fix: int64 vs float64 mismatch in `SELECT floor(i)`

### ISSUE THREAD

**Issue by GaoYusong** [apecloud/myduckserver#57]
```
 --- FAIL: TestQueriesSimple/SELECT_floor(i),_s_FROM_mytable_mt_ORDER_BY_floor(i)_DESC (0.09s)
        /Users/shannon/code/myduckserver/evaluation.go:726: 
            	Error Trace:	/Users/shannon/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.2-0.20240815142344-761713e36043/enginetest/evaluation.go:726
            	            				/Users/shannon/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.18.2-0.20240815142344-761713e36043/enginetest/evaluation.go:357
            	Error:      	Not equal: 
            	            	expected: []sql.Row{sql.Row{3, "third row"}, sql.Row{2, "second row"}, sql.Row{1, "first row"}}
            	            	actual  : []sql.Row{sql.Row{3, "third row"}, sql.Row{2, "second row"}, sql.Row{1, "first row"}}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -2,3 +2,3 @@
            	            	  (sql.Row) (len=2) {
            	            	-  (int64) 3,
            	            	+  (float64) 3,
            	            	   (string) (len=9) "third row"
            	            	@@ -6,3 +6,3 @@
            	            	  (sql.Row) (len=2) {
            	            	-  (int64) 2,
            	            	+  (float64) 2,
            	            	   (string) (len=10) "second row"
            	            	@@ -10,3 +10,3 @@
            	            	  (sql.Row) (len=2) {
            	            	-  (int64) 1,
            	            	+  (float64) 1,
            	            	   (string) (len=9) "first row"
            	Test:       	TestQueriesSimple/SELECT_floor(i),_s_FROM_mytable_mt_ORDER_BY_floor(i)_DESC
            	Messages:   	Unexpected result for query SELECT floor(i), s FROM mytable mt ORDER BY floor(i) DESC
```

**Comment by ddh-5230** [comment]
“DuckDB and MySQL’s SUM and FLOOR functions have different return rules for different types, as follows:”
duckdb:
sum(DECIMAL) -> DECIMAL
sum(SMALLINT) -> HUGEINT
sum(INTEGER) -> HUGEINT
sum(BIGINT) -> HUGEINT
sum(HUGEINT) -> HUGEINT
sum(DOUBLE) -> DOUBLE
floor(FLOAT) -> FLOAT
floor(DOUBLE) -> DOUBLE
floor(DECIMAL) -> DECIMAL

mysql:
sum(integer/DECIMAL) -> DECIMAL
sum(float/double) -> double
floor() -> int

i have already changed hugeint to int64. may we need to make any other modifications, and is it acceptable to tolerate some incompatibilities?”

**Comment by GaoYusong** [comment]
> “DuckDB and MySQL’s SUM and FLOOR functions have different return rules for different types, as follows:” duckdb: sum(DECIMAL) -> DECIMAL sum(SMALLINT) -> HUGEINT sum(INTEGER) -> HUGEINT sum(BIGINT) -> HUGEINT sum(HUGEINT) -> HUGEINT sum(DOUBLE) -> DOUBLE floor(FLOAT) -> FLOAT floor(DOUBLE) -> DOUBLE floor(DECIMAL) -> DECIMAL
> 
> mysql: sum(integer/DECIMAL) -> DECIMAL sum(float/double) -> double floor() -> int
> 
> i have already changed hugeint to int64. may we need to make any other modifications, and is it acceptable to tolerate some incompatibilities?”

welcome back!
